# Traefik v3 Configuration
global:
  checkNewVersion: false
  sendAnonymousUsage: false

# API and dashboard configuration
api:
  dashboard: true
  insecure: true
  debug: true

# Entry points
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"

# Provider configuration
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: app-network
  file:
    directory: /etc/traefik
    watch: true

# Certificate resolvers for Let's Encrypt
certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@yourdomain.com
      storage: /acme.json
      tlsChallenge: {}
      # For development, use staging server
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory

# Logging
log:
  level: INFO
  format: common

accessLog:
  format: common

# Metrics (optional)
metrics:
  prometheus:
    addEntryPointsLabels: true
    addServicesLabels: true

# Pilot (optional)
pilot:
  dashboard: false